var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                     xxx                                                        ",
   "                    xx!xx                                                       ",
   "                    x!!!x                    o o o                              ",
   "  xx                xx!xx                    xxxxx                              ",
   "  x                  xvx               o                                        ",
   "  x                                   xxx                                  o    ",
   "  x                                                                          x  ",
   "  x  @                  o                 z                      xxxxx       x  ",
   "  xxxxxxxxxx    xxxxxxxxxxxxxxx   xxxxxxxxxxxxsssxxxxx     xxxxxxx   xxssxxxxx  ",
   "           x    x             x   x                  x     x                    ",
   "           x!!!!x             x!!!x                  x!!!!!x                    ",
   "           x!!!!x             x!!!x                  x!!!!!x                    ",
   "           xxxxxx             xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "], 

  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                     xx                         ",
   "                             o                       x    o                     ",
   "   @                         x              o o o    x   xx                     ",
   "  xx                 o   xx       o          xxxxx   x      o                   ",
   "  x o               xx         o       o             x     xxx                  ",
   "  x                           xx      xxx            x                     o    ",
   "  x            xxx                                   x                       x  ",
   "  x  o o o o                                      z  x  xx    o  xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxx             xxxxxxxxxssssxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                   x!!!!!!!!!!!!!x                   x     x                    ",
   "                   x!!!!!!!!!!!!!x                   x!!!!!x                    ",
   "                   x!!!!!!!!!!!!!x                   x!!!!!x                    ",
   "                   xxxxxxxxxxxxxxx                   xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "], 

  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                         o      ",
   "                                                                        xx      ",
   "                                                                     xx         ",
   "                 o o            o o                                xx           ",
   "  @ z                                                            xx             ",
   "xxxxxxx  xx     xxxx     xx   xxxxxx   xxxxxxx!xxxxxxxxxxxxxxx   xxxxxxxsssxxxxx",
   "      x!!!!!!!!!!!!!!!!!!!!!!!x    x  o      xvx                x               ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!x    x                  o        xx               ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!x    x                xxxx        x               ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxx    x              o x  x        x               ",
   "                                   xxxxxxxxxxxxxxxxxx  xxxxxxxxxx               ",
   "                                                                                "],

  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "    @     oo    z     oo     z   oo     oo   z   oo    z    oo       oo         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],

   ["                                                                                ",
   "                                                                                 ",
   "   x     x                                                                       ",
   "   x     x  xxxx  x    x                                                         ",
   "   x     x x    x x    x                                                         ",
   "    x    x x    x x    x                                                         ",
   "      x    x    x x    x                                                         ",
   "      x    x    x x    x                                                         ",
   "      x     xxxx  xxxxxx                                                         ",
   "      x                                                                          ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "    x     x    x    x       x                                                    ",
   "    x     x    x    x x     x                                                    ",
   "    x  x  x    x    x  x    x                                                    ",
   "    x  x  x    x    x   x   x                                                    ",
   "    x  x  x    x    x    x  x                                                    ",
   "    x  x  x    x    x     x x                                                    ",
   "     x   x     x    x      xx                                                    ",
   "                                                                                 ",
   "                                                                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                 ",
   "                                                                                 "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
